server:
  port: 18082


spring:
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  sleuth:
    sampler:
      probability: 1
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411
    discovery-client-enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.137.22:3306/guli_sms
    username: root
    password: java0821
feign:
  sentinel:
    enabled: true
mybatis-plus:
  type-aliases-package: com.atguigu.gmall.sms.entity
  mapper-locations: classpath:mapper/sms/**/*.xml
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    com.atguigu.gmall: debug