server:
  port: 18083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:8411
    discovery-client-enabled: false
    sender:
      type: web
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: java0821
    url: jdbc:mysql://192.168.137.22:3306/guli_wms
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/wms/**/*.xml
  type-aliases-package: com.atguigu.gmall.wms.entity
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    com.atguigu.gmall: debug