server:
  port: 18084

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  sleuth:
    sampler:
      probability: 1
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411
    discovery-client-enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.137.22:3306/guli_ums
    username: root
    password: java0821
feign:
  sentinel:
    enabled: true
mybatis-plus:
  type-aliases-package: com.atguigu.gmall.ums.entity
  mapper-locations: classpath:mapper/ums/**/*.xml
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    com.atguigu.gmall: debug
